#!/usr/bin/env bash

function _buildkite_profile {
  local shome="${_buildkite_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/.buildkite/bin:$shome/bin:$PATH"

  BUILDKITE_VERSION="2.6.5"
}

_buildkite_profile
